name: Docker Image CICD

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag match_subtitles:$(date +%s)


  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: hub.sixtyfive.me
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
